# Generated by Django 3.2.3 on 2021-11-13 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnmpDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_Ip', models.CharField(max_length=15)),
                ('System_Description', models.CharField(max_length=1000)),
                ('System_Contact', models.CharField(max_length=1000)),
                ('System_Name', models.CharField(max_length=1000)),
                ('System_Location', models.CharField(max_length=1000)),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
