# Generated by Django 3.2.3 on 2022-01-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnmpDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpdevices',
            name='Community',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
